version: "3.8"

services:
  configserver:
    image: ciontcristian/configserver:latest
    build:
      context: ../ConfigService
      dockerfile: ../ConfigService/Dockerfile
    ports:
      - "8071:8071"
    networks:
      - ciontcristian-network

  companies:
    image: ciontcristian/companies:latest
    build:
      context: ../CompaniesService
      dockerfile: ../CompaniesService/Dockerfile
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
    depends_on:
      - configserver
    ports:
      - "8090:8090"
    environment:
      SPRING_PROFILES_ACTIVE: default
      SPRING_CONFIG_IMPORT: configserver:http://configserver:8071/
    networks:
      - ciontcristian-network

  jobs:
    image: ciontcristian/jobs:latest
    build:
      context: .
      dockerfile: Dockerfile
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
      #replicas: 2
    depends_on:
      - configserver
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: default
      SPRING_CONFIG_IMPORT: configserver:http://configserver:8071/
    networks:
      - ciontcristian-network

  users:
    image: ciontcristian/users:latest
    build:
      context: ../UsersService
      dockerfile: ../UsersService/Dockerfile
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
    depends_on:
      - configserver
    ports:
      - "9000:9000"
    environment:
      SPRING_PROFILES_ACTIVE: default
      SPRING_CONFIG_IMPORT: configserver:http://configserver:8071/
    networks:
      - ciontcristian-network

networks:
  ciontcristian-network: